apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tts-trainer-references
  labels:
    app: tts-trainer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tts-trainer-hf-cache
  labels:
    app: tts-trainer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
