apiVersion: v1
kind: Service
metadata:
  name: tts-trainer
  labels:
    app: tts-trainer
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: tts-trainer
